api_platform:
    version: 1.0.0
    eager_loading:
        fetch_partial: true
        max_joins: 5
        force_eager: false
    #mapping:
    #    paths:
    #        - '@OmedResourceBundle/Entity'
    enable_fos_user: true
    swagger:
         api_keys:
            apiKey:
                name: 'Authorization'
                type: 'header'
