parameters:
    '%env(resolve:DATABASE_URL)%': '%kernel.project_dir%/var/data'

doctrine:
    dbal:
        # configure these for your database server
        url: "%env(resolve:DATABASE_URL)%"
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            OmedResourceBundle:
                is_bundle: true
                type: annotation
                #dir: '@OmedResourceBundle/Entity'
                prefix: 'Omed\Resource\Entity'
                alias: Omed
